### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by FrancescElies** [flask-restful-swagger/flask-restful-swagger#15]
I could not see a  mailing list to ask, so I'm raising the question here. I hope It's fine.

I see this project being forked from https://github.com/rantav/flask-restful-swagger/ being @rantav the user with most contributions to both.

Which is the status of this project? Is it a refactoring of the previous one? Which of both projects would be recommended to use?

Thanks in advance for any help you could provide.

**Comment by sobolevn** [comment]
Hi! Thanks for your interest.

This project is a version 2 and a huge refactoring to the first version. But it is still not finished.
The basics are done, but we are suffering from lack of tests and migration docs.

This project is not production ready. I recommend you to use the master project. And I will highly appreciate any help on this project.

**Comment by FrancescElies** [comment]
Hi, 
thanks for you quick answer, at the moment we are considering some options with my colleagues. If in the end we decide for this project, we'll let you know if we can help.
All best, Francesc
